### Generated by Winemaker 0.7.4


SRCDIR                = .
SUBDIRS               =
DLLS                  =
EXES                  = wmahack3.exe



### Common settings

CEXTRA                = -mno-cygwin
CXXEXTRA              = -mno-cygwin
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          =
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =


### wmahack3.exe sources and settings

wmahack3_exe_MODULE   = wmahack3.exe
wmahack3_exe_C_SRCS   = wmahack.c
wmahack3_exe_CXX_SRCS =
wmahack3_exe_RC_SRCS  =
wmahack3_exe_LDFLAGS  = -mconsole \
			-mno-cygwin
wmahack3_exe_DLL_PATH =
wmahack3_exe_DLLS     = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
wmahack3_exe_LIBRARY_PATH=
wmahack3_exe_LIBRARIES= uuid

wmahack3_exe_OBJS     = $(wmahack3_exe_C_SRCS:.c=.o) \
			$(wmahack3_exe_CXX_SRCS:.cpp=.o) \
			$(wmahack3_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(wmahack3_exe_C_SRCS)
CXX_SRCS              = $(wmahack3_exe_CXX_SRCS)
RC_SRCS               = $(wmahack3_exe_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(EXES:%=%.so)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(EXES:%=%.so) $(EXES:%.exe=%)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(wmahack3_exe_MODULE).so: $(wmahack3_exe_OBJS)
	$(CC) $(wmahack3_exe_LDFLAGS) -o $@ $(wmahack3_exe_OBJS) $(wmahack3_exe_LIBRARY_PATH) $(DEFLIB) $(wmahack3_exe_DLLS:%=-l%) $(wmahack3_exe_LIBRARIES:%=-l%)


